# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-portfolio
  template:
    metadata:
      labels:
        app: nextjs-portfolio
    spec:
      containers:
        - name: portfolio
          # ⬇️ CHANGE THIS LINE ⬇️
          image: ghcr.io/praveen28-devops/heypraveen-portfolio:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10